---
ID: "e4e2528b-93f3-48fd-a430-dd58cf2a8ef1"
Parent: "27bd1a7e-77b6-4f1c-9f91-ef317149f541"
Template: "27bd1a7e-77b6-4f1c-9f91-ef317149f541"
Path: "/sitecore/templates/Project/fmc-custom-demo/Rendering Parameters/Social Proof/LogoCloud/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260928T101218Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2f74e55-1cbb-4b71-9101-67189387901c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260928T101218Z
