---
ID: "1ed2dc61-e6d3-4a81-82b2-c94ac5dc5f91"
Parent: "eb508c02-2cc4-47f0-a0fc-156488b7d580"
Template: "eb508c02-2cc4-47f0-a0fc-156488b7d580"
Path: "/sitecore/templates/Project/fmc-custom-demo/Folders/Quote Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{6038CD05-3166-4A7C-B0FA-505DEB204BD9}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "319f0859-98e1-4296-8d4f-86f82591339f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260921T093527Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "661a0532-ed92-4dc3-b354-18a5164abfe9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\damien.despas@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260921T093602Z
