// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { NextImage, RichText, Text, Link, AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import { cn } from '@/lib/utils';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { Sparkles } from 'lucide-react';
import * as LucideIcons from 'lucide-react';
import { isSodexoAboutPage, isSodexoSite } from '@/lib/sodexo-page';
import { SmartMedia } from '@/components/uiim/media/SmartMedia';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import componentMap from '.sitecore/component-map';
import Image from 'next/image';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'NextImage', value: NextImage },
      { name: 'RichText', value: RichText },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'AppPlaceholder', value: AppPlaceholder },
    ]
  },
  {
    module: '@/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Sparkles', value: Sparkles },
      { name: '*', value: LucideIcons },
    ]
  },
  {
    module: '@/lib/sodexo-page',
    exports: [
      { name: 'isSodexoAboutPage', value: isSodexoAboutPage },
      { name: 'isSodexoSite', value: isSodexoSite },
    ]
  },
  {
    module: '@/components/uiim/media/SmartMedia',
    exports: [
      { name: 'SmartMedia', value: SmartMedia },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
