'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useCallback, useEffect, useState, useRef, useMemo } from 'react';
import React from 'react';
import { useTranslations } from 'next-intl';
import { useSearchParams, useRouter as useRouter_38d453563358e259e30871f8ef5a0334c186c57e, usePathname } from 'next/navigation';
import { useSearch, useInfiniteSearch } from '@sitecore-content-sdk/nextjs/search';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { SearchEmptyResults } from '@/lib/search/search-components/SearchEmptyResults';
import { SearchError } from '@/lib/search/search-components/SearchError';
import { SearchItem } from '@/lib/search/search-components/SearchItem';
import { SearchSkeletonItem } from '@/lib/search/search-components/SearchSkeletonItem';
import { SearchPagination } from '@/lib/search/search-components/SearchPagination';
import { SearchInput } from '@/lib/search/search-components/SearchInput';
import { useEvent } from '@/lib/search/search-components/useEvent';
import { useRouter } from '@/lib/search/search-components/useRouter';
import { DICTIONARY_KEYS, DEFAULT_PAGE_SIZE, gridColsClass } from '@/lib/search/search-components/constants';
import Image from 'next/image';
import { Link, Text, NextImage, useSitecore, RichText, DateField, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { ChevronDown, Menu, X, User } from 'lucide-react';
import { SmartMedia } from '@/components/uiim/media/SmartMedia';
import { cn as cn_b4c06b3218abd6b3fb46a1f6d67407cec902c758 } from 'lib/utils';
import { SearchEmptyResults as SearchEmptyResults_a7fd5bb71665da1ba09c52ff7c1d1a533293f443 } from 'src/components/search-experience/search-components/SearchEmptyResults';
import { SearchError as SearchError_af1c5e83329285a922b0ebc80453dc52526cfbd2 } from 'src/components/search-experience/search-components/SearchError';
import { SearchItem as SearchItem_e885aa9244f141f046ded2862831f76da47607ba } from 'src/components/search-experience/search-components/SearchItem/index';
import { SearchSkeletonItem as SearchSkeletonItem_403b13df0ff93553534b1b8fbb933d0fa9d8fe7f } from 'src/components/search-experience/search-components/SearchSkeletonItem';
import { SearchPagination as SearchPagination_ffed64ef92a66188727c68b5c00211a86cf651fd } from 'src/components/search-experience/search-components/SearchPagination';
import { SearchInput as SearchInput_0a503da44320649691a090da01cb19bb1a143b00 } from 'src/components/search-experience/search-components/SearchInput';
import { useEvent as useEvent_807bf0b5175fcc2952aff70f7cb1d0f195c940af } from 'src/components/search-experience/search-components/useEvent';
import { useSearchField } from 'src/components/search-experience/search-components/useSearchField';
import { useParams } from 'src/components/search-experience/search-components/useParams';
import { DICTIONARY_KEYS as DICTIONARY_KEYS_f395c67553fa1a94298ee04894f3f430873be139, gridColsClass as gridColsClass_f395c67553fa1a94298ee04894f3f430873be139, DEFAULT_PAGE_SIZE as DEFAULT_PAGE_SIZE_f395c67553fa1a94298ee04894f3f430873be139, DEBOUNCE_TIME } from 'src/components/search-experience/search-components/constants';
import { useRouter as useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 } from 'src/components/search-experience/search-components/useRouter';
import { useDebouncedCallback } from 'src/components/search-experience/search-components/useDebounce';
import { event, pageView } from '@sitecore-content-sdk/events';
import { ItemCardFrame, ItemListFrame } from 'src/components/search-experience/search-components/SearchItemCommon';
import { SearchItemTitle } from 'src/components/search-experience/search-components/SearchItem/SearchItemTitle';
import { SearchItemSummary } from 'src/components/search-experience/search-components/SearchItem/SearchItemSummary';
import { SearchItemLink } from 'src/components/search-experience/search-components/SearchItem/SearchItemLink';
import { SearchItemCategory } from 'src/components/search-experience/search-components/SearchItem/SearchItemCategory';
import { SearchItemTags } from 'src/components/search-experience/search-components/SearchItem/SearchItemTags';
import { SearchItemImage } from 'src/components/search-experience/search-components/SearchItem/SearchItemImage';
import client from 'src/lib/sitecore-client';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useCallback', value: useCallback },
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useMemo', value: useMemo },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next-intl',
    exports: [
      { name: 'useTranslations', value: useTranslations },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useSearchParams', value: useSearchParams },
      { name: 'useRouter', value: useRouter_38d453563358e259e30871f8ef5a0334c186c57e },
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs/search',
    exports: [
      { name: 'useSearch', value: useSearch },
      { name: 'useInfiniteSearch', value: useInfiniteSearch },
    ]
  },
  {
    module: '@/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@/components/ui/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchEmptyResults',
    exports: [
      { name: 'SearchEmptyResults', value: SearchEmptyResults },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchError',
    exports: [
      { name: 'SearchError', value: SearchError },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchItem',
    exports: [
      { name: 'SearchItem', value: SearchItem },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchSkeletonItem',
    exports: [
      { name: 'SearchSkeletonItem', value: SearchSkeletonItem },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchPagination',
    exports: [
      { name: 'SearchPagination', value: SearchPagination },
    ]
  },
  {
    module: '@/lib/search/search-components/SearchInput',
    exports: [
      { name: 'SearchInput', value: SearchInput },
    ]
  },
  {
    module: '@/lib/search/search-components/useEvent',
    exports: [
      { name: 'useEvent', value: useEvent },
    ]
  },
  {
    module: '@/lib/search/search-components/useRouter',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@/lib/search/search-components/constants',
    exports: [
      { name: 'DICTIONARY_KEYS', value: DICTIONARY_KEYS },
      { name: 'DEFAULT_PAGE_SIZE', value: DEFAULT_PAGE_SIZE },
      { name: 'gridColsClass', value: gridColsClass },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'NextImage', value: NextImage },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'DateField', value: DateField },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'Menu', value: Menu },
      { name: 'X', value: X },
      { name: 'User', value: User },
    ]
  },
  {
    module: '@/components/uiim/media/SmartMedia',
    exports: [
      { name: 'SmartMedia', value: SmartMedia },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn_b4c06b3218abd6b3fb46a1f6d67407cec902c758 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchEmptyResults',
    exports: [
      { name: 'SearchEmptyResults', value: SearchEmptyResults_a7fd5bb71665da1ba09c52ff7c1d1a533293f443 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchError',
    exports: [
      { name: 'SearchError', value: SearchError_af1c5e83329285a922b0ebc80453dc52526cfbd2 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/index',
    exports: [
      { name: 'SearchItem', value: SearchItem_e885aa9244f141f046ded2862831f76da47607ba },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchSkeletonItem',
    exports: [
      { name: 'SearchSkeletonItem', value: SearchSkeletonItem_403b13df0ff93553534b1b8fbb933d0fa9d8fe7f },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchPagination',
    exports: [
      { name: 'SearchPagination', value: SearchPagination_ffed64ef92a66188727c68b5c00211a86cf651fd },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchInput',
    exports: [
      { name: 'SearchInput', value: SearchInput_0a503da44320649691a090da01cb19bb1a143b00 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useEvent',
    exports: [
      { name: 'useEvent', value: useEvent_807bf0b5175fcc2952aff70f7cb1d0f195c940af },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useSearchField',
    exports: [
      { name: 'useSearchField', value: useSearchField },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useParams',
    exports: [
      { name: 'useParams', value: useParams },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/constants',
    exports: [
      { name: 'DICTIONARY_KEYS', value: DICTIONARY_KEYS_f395c67553fa1a94298ee04894f3f430873be139 },
      { name: 'gridColsClass', value: gridColsClass_f395c67553fa1a94298ee04894f3f430873be139 },
      { name: 'DEFAULT_PAGE_SIZE', value: DEFAULT_PAGE_SIZE_f395c67553fa1a94298ee04894f3f430873be139 },
      { name: 'DEBOUNCE_TIME', value: DEBOUNCE_TIME },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useRouter',
    exports: [
      { name: 'useRouter', value: useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useDebounce',
    exports: [
      { name: 'useDebouncedCallback', value: useDebouncedCallback },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'event', value: event },
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItemCommon',
    exports: [
      { name: 'ItemCardFrame', value: ItemCardFrame },
      { name: 'ItemListFrame', value: ItemListFrame },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTitle',
    exports: [
      { name: 'SearchItemTitle', value: SearchItemTitle },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemSummary',
    exports: [
      { name: 'SearchItemSummary', value: SearchItemSummary },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemLink',
    exports: [
      { name: 'SearchItemLink', value: SearchItemLink },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemCategory',
    exports: [
      { name: 'SearchItemCategory', value: SearchItemCategory },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTags',
    exports: [
      { name: 'SearchItemTags', value: SearchItemTags },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemImage',
    exports: [
      { name: 'SearchItemImage', value: SearchItemImage },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
