// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { NextImage, RichText, Text, Link, AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import { cn } from '@/lib/utils';
import { isSodexoArticlesPage, isSodexoSite, isSodexoAboutPage, isSodexoHelpPage, isSodexoBrandDetailPage, isSodexoBrandsPage } from '@/lib/sodexo-page';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { isModernRecipeSite, MR } from '@/lib/modern-recipe-page';
import { ModernRecipeFooterView, ModernRecipeGalleryView, ModernRecipePillarsView } from '@/components/uiim/modern-recipe/ModernRecipeViews';
import { Sparkles } from 'lucide-react';
import * as LucideIcons from 'lucide-react';
import { brandStyleVars, getPageBrandStyle, resolveBrandStyle, BRAND_STYLE_TOKENS } from '@/lib/sodexo-brand-style';
import { SODEXO_BRAND_PILLAR_ICONS, SODEXO_BRAND_HERO_POSTERS, SODEXO_BRAND_LOGOS } from '@/lib/sodexo-brands-media';
import { SmartMedia } from '@/components/uiim/media/SmartMedia';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import componentMap from '.sitecore/component-map';
import Image from 'next/image';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'NextImage', value: NextImage },
      { name: 'RichText', value: RichText },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'AppPlaceholder', value: AppPlaceholder },
    ]
  },
  {
    module: '@/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@/lib/sodexo-page',
    exports: [
      { name: 'isSodexoArticlesPage', value: isSodexoArticlesPage },
      { name: 'isSodexoSite', value: isSodexoSite },
      { name: 'isSodexoAboutPage', value: isSodexoAboutPage },
      { name: 'isSodexoHelpPage', value: isSodexoHelpPage },
      { name: 'isSodexoBrandDetailPage', value: isSodexoBrandDetailPage },
      { name: 'isSodexoBrandsPage', value: isSodexoBrandsPage },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: '@/lib/modern-recipe-page',
    exports: [
      { name: 'isModernRecipeSite', value: isModernRecipeSite },
      { name: 'MR', value: MR },
    ]
  },
  {
    module: '@/components/uiim/modern-recipe/ModernRecipeViews',
    exports: [
      { name: 'ModernRecipeFooterView', value: ModernRecipeFooterView },
      { name: 'ModernRecipeGalleryView', value: ModernRecipeGalleryView },
      { name: 'ModernRecipePillarsView', value: ModernRecipePillarsView },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'Sparkles', value: Sparkles },
      { name: '*', value: LucideIcons },
    ]
  },
  {
    module: '@/lib/sodexo-brand-style',
    exports: [
      { name: 'brandStyleVars', value: brandStyleVars },
      { name: 'getPageBrandStyle', value: getPageBrandStyle },
      { name: 'resolveBrandStyle', value: resolveBrandStyle },
      { name: 'BRAND_STYLE_TOKENS', value: BRAND_STYLE_TOKENS },
    ]
  },
  {
    module: '@/lib/sodexo-brands-media',
    exports: [
      { name: 'SODEXO_BRAND_PILLAR_ICONS', value: SODEXO_BRAND_PILLAR_ICONS },
      { name: 'SODEXO_BRAND_HERO_POSTERS', value: SODEXO_BRAND_HERO_POSTERS },
      { name: 'SODEXO_BRAND_LOGOS', value: SODEXO_BRAND_LOGOS },
    ]
  },
  {
    module: '@/components/uiim/media/SmartMedia',
    exports: [
      { name: 'SmartMedia', value: SmartMedia },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
