---
ID: "9b27a710-5d47-4a70-a06b-72fc37f022ae"
Parent: "449fe2dc-8d9a-439e-8bb1-6ebb01d43083"
Template: "449fe2dc-8d9a-439e-8bb1-6ebb01d43083"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Search/SearchCollection/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260817T164252Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e1808e6-5fd8-4e00-9c75-fa0f4184f9df"
    - ID: "8e8c5310-a28e-4e73-b79b-8e800edc39ca"
      Hint: SortOrder
      Value: desc
    - ID: "af6bc28f-f6ca-4728-8055-f2d1823d195d"
      Hint: MaxItems
      Value: 3
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260817T164252Z
